# Generated by Django 4.0.5 on 2022-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
