# Generated by Django 4.0.5 on 2022-06-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
