# Generated by Django 4.0.5 on 2022-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_first_name_account_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
